Correct 'typo'
Avoids the error:
Vagrantfile:42:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)